// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhnzbxbrvnutghdmzffu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxobnpieGJydm51dGdoZG16ZmZ1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NDQ2MTAsImV4cCI6MjA1NzUyMDYxMH0.sVhwsJQI6e6eHMn1yZjvtDz_GbWF4RjnqlvpuuuTzBo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);